# The periodic table. 
#
# Got that from [1]. Finding such a list on the net is not as easy as you might
# think. Search for "list of chemical elements".
#
# Replaced masses like
#   9.012182(3) -> 9.012182
#   [227]       -> 227
#
# [1] http://chemistry.about.com/od/elementfacts/a/atomicweights.htm

pt={\
'H':     {'number': 1  , 'mass': 1.00794         },                                   
'He':    {'number': 2  , 'mass': 4.002602        },                        
'Li':    {'number': 3  , 'mass': 6.941           },                     
'Be':    {'number': 4  , 'mass': 9.012182        },                        
'B':     {'number': 5  , 'mass': 10.811          },                      
'C':     {'number': 6  , 'mass': 12.0107         },                       
'N':     {'number': 7  , 'mass': 14.0067         },                       
'O':     {'number': 8  , 'mass': 15.9994         },                       
'F':     {'number': 9  , 'mass': 18.9984032      },                          
'Ne':    {'number': 10 , 'mass': 20.1797         },                       
'Na':    {'number': 11 , 'mass': 22.98976928     },                           
'Mg':    {'number': 12 , 'mass': 24.3050         },                       
'Al':    {'number': 13 , 'mass': 26.9815386      },                          
'Si':    {'number': 14 , 'mass': 28.0855         },                       
'P':     {'number': 15 , 'mass': 30.973762       },                         
'S':     {'number': 16 , 'mass': 32.065          },                      
'Cl':    {'number': 17 , 'mass': 35.453          },                      
'Ar':    {'number': 18 , 'mass': 39.948          },                      
'K':     {'number': 19 , 'mass': 39.0983         },                       
'Ca':    {'number': 20 , 'mass': 40.078          },                      
'Sc':    {'number': 21 , 'mass': 44.955912       },                         
'Ti':    {'number': 22 , 'mass': 47.867          },                      
'V':     {'number': 23 , 'mass': 50.9415         },                       
'Cr':    {'number': 24 , 'mass': 51.9961         },                       
'Mn':    {'number': 25 , 'mass': 54.938045       },                         
'Fe':    {'number': 26 , 'mass': 55.845          },                      
'Co':    {'number': 27 , 'mass': 58.933195       },                         
'Ni':    {'number': 28 , 'mass': 58.6934         },                       
'Cu':    {'number': 29 , 'mass': 63.546          },                      
'Zn':    {'number': 30 , 'mass': 65.38           },                     
'Ga':    {'number': 31 , 'mass': 69.723          },                      
'Ge':    {'number': 32 , 'mass': 72.64           },                     
'As':    {'number': 33 , 'mass': 74.92160        },                        
'Se':    {'number': 34 , 'mass': 78.96           },                     
'Br':    {'number': 35 , 'mass': 79.904          },                      
'Kr':    {'number': 36 , 'mass': 83.798          },                      
'Rb':    {'number': 37 , 'mass': 85.4678         },                       
'Sr':    {'number': 38 , 'mass': 87.62           },                     
'Y':     {'number': 39 , 'mass': 88.90585        },                        
'Zr':    {'number': 40 , 'mass': 91.224          },                      
'Nb':    {'number': 41 , 'mass': 92.90638        },                        
'Mo':    {'number': 42 , 'mass': 95.96           },                     
'Tc':    {'number': 43 , 'mass': 98              },                  
'Ru':    {'number': 44 , 'mass': 101.07          },                      
'Rh':    {'number': 45 , 'mass': 102.90550       },                         
'Pd':    {'number': 46 , 'mass': 106.42          },                      
'Ag':    {'number': 47 , 'mass': 107.8682        },                        
'Cd':    {'number': 48 , 'mass': 112.411         },                       
'In':    {'number': 49 , 'mass': 114.818         },                       
'Sn':    {'number': 50 , 'mass': 118.710         },                       
'Sb':    {'number': 51 , 'mass': 121.760         },                       
'Te':    {'number': 52 , 'mass': 127.60          },                      
'I':     {'number': 53 , 'mass': 126.90447       },                         
'Xe':    {'number': 54 , 'mass': 131.293         },                       
'Cs':    {'number': 55 , 'mass': 132.9054519     },                           
'Ba':    {'number': 56 , 'mass': 137.327         },                       
'La':    {'number': 57 , 'mass': 138.90547       },                         
'Ce':    {'number': 58 , 'mass': 140.116         },                       
'Pr':    {'number': 59 , 'mass': 140.90765       },                         
'Nd':    {'number': 60 , 'mass': 144.242         },                       
'Pm':    {'number': 61 , 'mass': 145             },                   
'Sm':    {'number': 62 , 'mass': 150.36          },                      
'Eu':    {'number': 63 , 'mass': 151.964         },                       
'Gd':    {'number': 64 , 'mass': 157.25          },                      
'Tb':    {'number': 65 , 'mass': 158.92535       },                         
'Dy':    {'number': 66 , 'mass': 162.500         },                       
'Ho':    {'number': 67 , 'mass': 164.93032       },                         
'Er':    {'number': 68 , 'mass': 167.259         },                       
'Tm':    {'number': 69 , 'mass': 168.93421       },                         
'Yb':    {'number': 70 , 'mass': 173.054         },                       
'Lu':    {'number': 71 , 'mass': 174.9668        },                        
'Hf':    {'number': 72 , 'mass': 178.49          },                      
'Ta':    {'number': 73 , 'mass': 180.94788       },                         
'W':     {'number': 74 , 'mass': 183.84          },                      
'Re':    {'number': 75 , 'mass': 186.207         },                       
'Os':    {'number': 76 , 'mass': 190.23          },                      
'Ir':    {'number': 77 , 'mass': 192.217         },                       
'Pt':    {'number': 78 , 'mass': 195.084         },                       
'Au':    {'number': 79 , 'mass': 196.966569      },                          
'Hg':    {'number': 80 , 'mass': 200.59          },                      
'Tl':    {'number': 81 , 'mass': 204.3833        },                        
'Pb':    {'number': 82 , 'mass': 207.2           },                     
'Bi':    {'number': 83 , 'mass': 208.98040       },                         
'Po':    {'number': 84 , 'mass': 209             },                   
'At':    {'number': 85 , 'mass': 210             },                   
'Rn':    {'number': 86 , 'mass': 222             },                   
'Fr':    {'number': 87 , 'mass': 223             },                   
'Ra':    {'number': 88 , 'mass': 226             },                   
'Ac':    {'number': 89 , 'mass': 227             },                   
'Th':    {'number': 90 , 'mass': 232.03806       },                         
'Pa':    {'number': 91 , 'mass': 231.03588       },                         
'U':     {'number': 92 , 'mass': 238.02891       },                         
'Np':    {'number': 93 , 'mass': 237             },                   
'Pu':    {'number': 94 , 'mass': 244             },                   
'Am':    {'number': 95 , 'mass': 243             },                   
'Cm':    {'number': 96 , 'mass': 247             },                   
'Bk':    {'number': 97 , 'mass': 247             },                   
'Cf':    {'number': 98 , 'mass': 251             },                   
'Es':    {'number': 99 , 'mass': 252             },                   
'Fm':    {'number': 100, 'mass': 257             },                   
'Md':    {'number': 101, 'mass': 258             },                   
'No':    {'number': 102, 'mass': 259             },                   
'Lr':    {'number': 103, 'mass': 262             },                   
'Rf':    {'number': 104, 'mass': 267             },                   
'Db':    {'number': 105, 'mass': 268             },                   
'Sg':    {'number': 106, 'mass': 271             },                   
'Bh':    {'number': 107, 'mass': 272             },                   
'Hs':    {'number': 108, 'mass': 270             },                   
'Mt':    {'number': 109, 'mass': 276             },                   
'Ds':    {'number': 110, 'mass': 281             },                   
'Rg':    {'number': 111, 'mass': 280             },                   
'Uub':   {'number': 112, 'mass': 285             },                   
'Uut':   {'number': 113, 'mass': 284             },                   
'Uuq':   {'number': 114, 'mass': 289             },                   
'Uup':   {'number': 115, 'mass': 288             },                   
'Uuh':   {'number': 116, 'mass': 293             },                   
'Uuo':   {'number': 118, 'mass': 294             },                    
}
